---
  jira_api_url:
    description: "Jira API URL"
    type: "string"
    default: "https://bitovi.atlassian.net"
    required: true
  verify:
    description: "Verify SSL certificate. Set to False to disable verification. Default True"
    type: boolean
    default: True
  auth_method:
    description: "Authentication method to use - oauth, basic or pat"
    type: "string"
    secret: false
    required: true
    default: "oauth"
    enum:
      - basic
  username:
    description: "Username if using the basic or cookie auth_method"
    type: "string"
    secret: false
    required: false
  password:
    description: "Password if using the basic or cookie auth_method"
    type: "string"
    secret: true
    required: false
  project:
    description: "Project to be used as default for actions that don't require or allow a project"
    type: "string"
    secret: false
    required: true
    default: "ST2DEMO"







 
