---
  jira_api_url:
    description: "Jira API URL"
    type: "string"
    default: "https://bitovi.atlassian.net/"
    required: true
  verify:
    description: "Verify SSL certificate. Set to False to disable verification. Default True"
    type: boolean
    default: True
  auth_method:
    description: "Authentication method to use - oauth, basic or pat"
    type: "string"
    secret: false
    required: true
    default: "oauth"
    enum:
      - basic
      - cookie
  username:
    description: "Username if using the basic or cookie auth_method"
    type: "string"
    secret: false
    required: false
  password:
    description: "Password if using the basic or cookie auth_method"
    type: "string"
    secret: true
    required: false
  project:
    description: "Project to be used as default for actions that don't require or allow a project"
    type: "string"
    secret: false
    required: true
  # jira_svc_account:
  #   description: "Jira service account name"
  #   type: "string"
  #   default: "username"
  #   required: true
  # jira_svc_password:
  #   description: "Jira service Account Password if using the basic auth_method. Necessary for component posting through Jira's REST API."
  #   type: "string"
  #   default: ""
  #   secret: true
  #   required: true







 
