---
name: create_issue
pack: mock_jira
description: Create a new JIRA issue / ticket.
enabled: true

trigger:
  type: core.st2.webhook
  parameters:
      url: create-jira-issue

criteria:
  trigger.body.webhookEvent:
    type: equals
    pattern: create

action:
    ref: mock_jira.create_issue
    parameters:
      trigger: "{{ trigger }"