---
name: update_field
pack: mock_jira
description: update JIRA issue / ticket.
enabled: true

trigger:
  type: core.st2.webhook
  parameters:
      url: "transition-jira-issue"

criteria:
  trigger.body.webhookEvent:
    type: regex
    pattern: "update field jira issue"

action:
    ref: mock_jira.update_field_value
    parameters:
      update_data: "{{trigger.body}}"